name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v2
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        working-directory: ./backend
        run: mvn --batch-mode --update-snapshots verify

      - name: Generate JaCoCo Badge
        if: always()
        id: jacoco
        uses: fasanosalvatore/jacoco-badge-generator@eb546ec4cab35c3cf1b22f087bf099d4242e33fd
        with:
          jacoco-csv-file: backend/target/site/jacoco-merged-test-coverage-report/jacoco.csv
          generate-branches-badge: true
          branches-text: coverage

      - name: Move CheckStyle badge
        if: always()
        run: mv ./backend/target/site/badges/checkstyle-result.svg ./.github/badges/

      - name: Delete old JavaDoc
        run: rm -rf docs

      - name: Generate JavaDoc
        working-directory: ./backend
        run: mvn javadoc:javadoc

      - name: Take JaCoCo report
        run: rm -rf JaCoCo-Coverage-Report && mv ./backend/target/site/jacoco-merged-test-coverage-report/ JaCoCo-Coverage-Report/

      - name: Commit and push generated files
        if: always()
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: 'docs: add generated docs files'
          add: '["*.svg", "docs", "JaCoCo-Coverage-Report"]'
